export const TETRISSCORE = 'TETRISSCORE'
export const TETRISLEVEL = 'TETRISLEVEL'
export const TETRISLINES = 'TETRISLINES'
export const TETRISSTATE = 'TETRISSTATE'

export const GETINFO_EVENT = 'GETINFOEVENT'
export const RECEIVE_INFO_EVENT_MUSIC = "RECEIVEINFOEVENTMUSIC"
